#:kivy 2.0.0

<LoginScreen>
	canvas.before:
		Color: 
			rgba: [1., 1., 1., 1]
		Rectangle:
			pos: self.pos
			size: self.size

	orientation: "vertical"
	spacing: 10
	padding: [self.width * 0.05, self.height * 0.05]      # Need to be a percentage of height/width

	Label:
		text: 'TESTING LABEL TEXT'
		size_hint: (1, 0.3)
		font_size: 35
		color: [0, 0, 0, 1]

	Button:
		text: 'This is 30pt'
		size_hint: 0.5, 0.05
		font_size: 30
		pos_hint: {'center_x': 0.5}
		background_normal: ''
		background_color: [0.906, 0.906, 0.906, 1]
		color: [0, 0, 0, 1]

	Button:
		text: 'This is 30dp'
		size_hint: 0.5, 0.05
		font_size: dp(30)
		pos_hint: {'center_x': 0.5}
		background_normal: ''
		background_color: [0.906, 0.906, 0.906, 1]
		color: [0, 0, 0, 1]

	Button:
		text: 'This is 30sp'
		size_hint: 0.5, 0.05
		font_size: sp(30)
		pos_hint: {'center_x': 0.5}
		background_normal: ''
		background_color: [0.906, 0.906, 0.906, 1]
		color: [0, 0, 0, 1]

	Button:
		text: 'This one resizes!'
		size_hint: (0.5, 0.05)
		font_size: root.test_font_size
		pos_hint: {'center_x': 0.5}
		background_normal: ''
		background_color: [0.906, 0.906, 0.906, 1]
		color: [0, 0, 0, 1]


